version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: axios
    versions:
    - "> 0.19.2, < 0.20"
  - dependency-name: axios
    versions:
    - "> 0.20.0, < 1"
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
    - 4.5.0
  - dependency-name: webpack
    versions:
    - 5.24.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.1.1
